run-1:
	cd Q1 && rm -f main && gcc -pthread Q1.c -o main && ./main

run-2:
	cd Q2 && rm -f main && gcc -pthread Q2.c -o main && ./main

run-3:
	cd Q3 && rm -f main && gcc -pthread Q3.c -o main && ./main

run-4:
	cd Q4 && rm -f main && gcc -pthread Q4.c -o main && ./main

run-5:
	cd Q5 && rm -f main && gcc -pthread Q5.c -o main && ./main

run-6:
	cd Q6 && rm -f main && gcc -pthread Q6.c -o main && ./main

run-7:
	cd Q7 && rm -f main && gcc -pthread Q7.c -o main && ./main



